---
title: "revealJS로 PT 파일 만들기"
author: "eunkwang"
date: '`r Sys.Date()`'
output: 
  html_document: 
    toc: yes
---

<hr>

## Motivation

본 문서는 revealJS 템플릿을 이용하여 PT파일을 작성하고자 할 때 유용하게 사용할만한 내용들을 정리하였음.    
Rstudio 에서 기본적으로 제공하는 프레젠테이션 용 템플릿은 revealJS 이외에도 ioslides 와 slidy 가 있으나 간단하게 템플릿을 활용하는 것은 reavealJS 가 뛰어남    
그러나 CSS 커스터마이징이 가능하다면 slidy가 장점이 많음

## 문서 구성 요소

문서는 다음과 같이 세개의 파트로 나눠져 있음

1. yaml : 문서의 설정 정보를 저장하는 yaml 부분 '---' 으로 영역을 지정하며 html 문서의 타입에 따라 제공하는 옵션의 차이가 있음
2. markdown : 마크다운 문법으로 작성하는 에디터 영역이며 HTML 태그도 사용 가능함
3. codebox : "```"으로 영역으르 지정하며 코드 박스를 지정할 수 있음

<hr>

## yaml 작성 방법

revealjs를 콘트롤 하기 위해서는 문서 상단에 PT의 config을 다음과 같이 기록해야 하며 이에 대한 규칙은 기본적으로 yaml 문법을 따르나 다른 템플릿 패키지와 차이가 있음

>title: "PT 파일 테스트 하기"    
output:   
  revealjs::revealjs_presentation:    
    theme: sky  # (테마 적용)   
    highlight: pygments  # (신텍스 하이라이터 설정 옵션)    
    center: TRUE  # (가운대 정렬 옵션)    
    self_contained: false  # (???)    
    reveal_options:  # (추가 옵션)    
      slideNumber: true   
      previewLinks: true    


revealjs 에서는 다음과 같은 다양 한 기본 테마를 제공하며 yaml 에서 theme 파라미터 값을 변경하여 적용할 수 있음

>"default", "simple", "sky", "beige", "serif", "solarized", "blood", "moon", "night", "black", "league" or "white"

추가로 사용 가능한 옵션은 아래 링크를 참고하면 됨

https://github.com/hakimel/reveal.js#configuration


## 페이지 구조만들기

1. '#' 는 페이지의 1st Depth 페이지로 좌우로 이동함
    + 기본적으로 간지의 역할을 함
2. '##' 는 페이지의 2nd Depth 페이지로 상하로 이동함
    + 기본적으로 페이지의 제목 역할을 함
3. '##' 는 페이지의 Head Message 영역에 위치함
4. '----' 는 페이지 분할 심볼임


## 리스트 블릿 사용하기

> - 블릿 애니메이션은 '-, *' symbol을 이용하여 작성할 수 있음
- 리스트 블릿 앞에 '>' 을 붙이면 리스트 애니메이션으로 동작함 
- '> -' 문법은 ## 로 작성된 페이지에서만 작동됨


## 애니메이션 삽입하기

Chunk 옵션에 다음과 같이 fig.show = "animate", interval = .05, cache = T 를 설정하여 loop 에서 생성되는 이미지 묶음을 하나의 영상으로 인코딩 하는 것이 가능함

> {r example, fig.height = 5, fig.show = "animate", interval = .05, echo = F, cache = T}    
  x <- c(0, 1, 2, 3)    
  y <- c(0, 2, 3, 4)    
  for(i in 1:400){    
    add_x <- abs(rnorm(1))    
  add_y <- add_x + abs(rnorm(1))    
  x <- append(x, add_x)   
  y <- append(y, add_y)   
  pd <- data.frame(y, x)    
  p <- ggplot(pd, aes(x = x, y = y)) + geom_point() +     
    stat_smooth(method = "loess") +     
    lims(x = c(0, 3), y = c(0, 4))    
  print(p)    
}   

그러나 영상 처리 시 코덱에 따라 인코딩 문제가 발생 할 수 있어 최종 결과물에 문제가 있으면 영상 인코딩을 다시 해야 함. 인코딩 명령은 BASH Shell 에서 다음과 같은 명령어를 통해 위 코드에서 생성된 이미지를 다시 인코딩 할 수 있음


```{bash eval = FALSE}
ffmpeg -y -r 20 -i output/figure/example-%d.png -c:v libvpx -minrate 1M -crf 10 output/figure/resultVideo.webm
```


## 화면 횡으로 나누기

슬라이드에서 화면을 횡으로 나눠서 표기 하기 위해서는 다음과 같이 처리해야 함

```{css eval = FALSE}
<style>
.container{
    display: flex;
}
.col{
    flex: 1;
}
</style>
  
<div class="container">
  
<div class="col">
* 과거
    + PPT 기반의 분석 보고서
    + 가설 기반의 커스텀 리서치
    + 통계학 기반의 분석가
    + 지표 분석 중심의 비즈니스 분석
</div>
<div class="col">
* 현재
    + **재현 가능한 분석 보고서**
    + **분석 자동화 개발**
    + **예측과 최적화를 위한 분석 모델 개발(프로토타이핑)**
    + **데이터 시각화 대시보드 서비스 개발**
    + **정성/정량 분석의 통합**
</div>
```


## 참고자료

revealjs 에대한 전반적인 기능 설명을 하는 웹 사이트
https://github.com/rstudio/revealjs#overview


## 기타문제

그 외 슬라이드 이동문제가 생기는 경우가 있는데 이에 대해서는 아직 완벽한 해결책을 찾지는 못한 상황임
